name: CI

on: 
  workflow_dispatch:


jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 356
    steps:
    - uses: actions/checkout@v4
    - name: Testing
      uses: rdp-studio/ssh2actions@main
